HW2
earakelianEPAM/EdgarArakelianMobile pull request #1
Opened 2023-02-07 11:54 UTC by earakelianEPAM

2023-02-10 21:27 UTC, MaksimMeshcheriakovTR requested changes
В целом все очень хорошо, за исключением нерелевантной проверки в webTest - поправьте пожалуйста.

2023-02-10 21:27 UTC, MaksimMeshcheriakovTR commented on src/test/java/scenarios/webMobileTests.java
> +        for (int i = ZERO; i < THREE; i++) {
Фактически проверка нерелевантная: почему только 3 элемента? Почему не 1, 5, 250? Чем 3 лучше этих цифр? (подсказка: вспомните или погуглите про домены эквивалентности и наилучших представителей, ну и анализ граничных значений туда же). Что мешает проверить все элементы списка рез-тов?
Рекомендую кстати освоить стримы (не в качестве требования к этой работе, просто замечание по поводу): то же самое делается значительно короче, проще и элегантнее.

2023-02-10 21:27 UTC, MaksimMeshcheriakovTR commented on src/test/resources/nativeTest.properties
> +password=qwerty1234
для целей нашей работы это допустимо, но вообще на будущее лучше выработать привычку никогда, не при каких условиях не хранить креды в коде и конфигах. Используйте environment, специальные защищенные (или хотя бы отделно сконфигуренные) БД и т. п. Кстати, в третьей работе это будет обязательным требованием.

2023-02-10 21:27 UTC, MaksimMeshcheriakovTR commented on src/main/java/pageObjects/webTest/WebPageObject.java
> +    public WebPageObject searchEpam(String searchStr) {
плохой нейминг: в название метода (!) содержится паттерн поиска. А если захотите искать что-нибудь другое, не ЕПАМ? Метод-то у вас не зря же параметризован.

2023-02-10 21:27 UTC, MaksimMeshcheriakovTR commented on src/main/java/pageObjects/nativeTest/NativePageObject.java
> +public class NativePageObject extends BasePage {
На мой взгляд, название неудачное: не отражает сути описываемого объекта. Лучше было бы например LoginPageObject или MainPageObject

2023-02-12 10:34 UTC, earakelianEPAM commented on src/test/java/scenarios/webMobileTests.java
> +        for (int i = ZERO; i < THREE; i++) {
Поправил логику теста, теперь проверка не на количество найденных элементов, а на найденный текст в элементах, что тоже соответствует, как мне кажется, требованию в ДЗ и Вашему комментарию :)

2023-02-12 10:34 UTC, earakelianEPAM commented on src/main/java/pageObjects/webTest/WebPageObject.java
> +    public WebPageObject searchEpam(String searchStr) {
Скорректировал

2023-02-12 10:34 UTC, earakelianEPAM commented on src/main/java/pageObjects/nativeTest/NativePageObject.java
> +public class NativePageObject extends BasePage {
Скорректировал

2023-02-16 19:53 UTC, MaksimMeshcheriakovEPAM requested changes
На этоттраз ложноположительный тест - см. коммент. 
Для таких случаев рекомендуется использовать soft assert, хотя можно и самому аккумулятор написать.

2023-02-16 19:53 UTC, MaksimMeshcheriakovEPAM commented on src/main/java/pageObjects/webTest/WebPageObject.java
> +                return true;
Теперь у вас ложноположительный тест: метод вернет true на первом же удовлетворяющем вхождении, остальные проверять не станет. Даже если перед этим было N не содержащих нужный паттерн вхождений, что является unexpected result. 
False ваш тест вернет только в случае отсутствия паттерна во ВСЕХ результатх поиска.

2023-02-17 13:21 UTC, earakelianEPAM commented on src/main/java/pageObjects/webTest/WebPageObject.java
> +                return true;
Поправил.

2023-02-17 14:35 UTC, MaksimMeshcheriakovTR approved these changes
Поправка принимается, работа зачтена.

2023-02-17 14:43 UTC, merged